name: 'Deploy to Production'

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@v2'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '20'

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
