name: 'Deploy to Production'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable containerregistry.googleapis.com

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/nextjs-app .
          docker push gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/nextjs-app

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy nextjs-service \
            --image gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/nextjs-app \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
