name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/frontend .
          docker push gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy nextjs-service \
            --image gcr.io/${{ secrets.CLOUD_RUN_PROJECT_NAME }}/frontend \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
